version: '2'
services:
  nginx_1:
    image: nginx
    depends_on:
      - registrator
    expose:
      - "8001"
    ports:
      - '8001:80'
    environment:
      - VIRTUAL_HOST=nginx_1

  nginx_2:
    image: nginx
    depends_on:
      - registrator
    expose:
      - "8001"
    ports:
      - '8002:80'
    environment:
      - VIRTUAL_HOST=nginx_2

  linkerd:
    image: buoyantio/linkerd:0.7.2
    container_name: linkerd
    depends_on:
      - registrator
    ports: ["4140:4140", "9990:9990"]
    volumes: ["./conf:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/sample_linkerd.yml


  namerd:
    image: buoyantio/namerd:0.7.2
    container_name: namerd
    depends_on:
      - registrator
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./conf:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/sample_namerd.yml


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - registrator
    ports:
      - "8888:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  consul:
    image: "gliderlabs/consul-server"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-bootstrap"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: "-internal consul://consul:8500"
